"""empty message

Revision ID: 11edc9bf2671
Revises: b26cd8ed5898
Create Date: 2018-05-17 14:38:30.114263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11edc9bf2671'
down_revision = 'b26cd8ed5898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fk_users',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('company', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fk_users')
    # ### end Alembic commands ###
